// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{
    type: 'autogenerated',
    dirName: '.'
  }],
  // docs: [{
  //   type: 'category',
  //   label: 'spec',
  //   link: { type: 'doc', id: 'specification' },
  //   items: [],
  // }],
};

module.exports = sidebars;
